Device branch
Divinity-dev/Blog-App pull request #9
Opened 2023-05-24 19:15 UTC by Divinity-dev

In this phase of the project, I have implemented the following, by adding a device;
1. Allow a user to register
2. User can log in with email and password
3. password stored in a database
4. reset the password 
5. ask for confirmation of email

2023-05-24 19:30 UTC, VICTOR-CHUKWU requested changes
Hi @Divinity-dev  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed
- devise added


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 19:30 UTC, VICTOR-CHUKWU commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
- [ ] The application should ask for confirmation by email. kindly add confirmable to devise

2023-05-25 11:07 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @Divinity-dev, Team👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- Good job with authentication. ✔️
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 11:12 UTC, merged

2023-05-25 11:46 UTC, Divinity-dev commented
Thank you 

Sent from Yahoo Mail on Android 
 
  On Thu, May 25, 2023 at 12:08 PM, Ranjeet ***@***.***> wrote:   


@thecodechaser approved this pull request.

STATUS: APPROVED 🟢
 
Hi @Divinity-dev, Team 👋 ,

Your project is complete! There is nothing else to say other than... it's time to merge it 
Congratulations! 🎉
 
To Highlight 🎉
    
   - Good job with authentication. ✔️
   - No linter errors. ✔️
   - Gitflow is followed. ✔️
   - Professional README file. ✔️
   - PR has a good title and summary. ✔️



Cheers and Happy coding! 👏 👏 👏
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>